package nutri_advanced;

import javax.swing.JOptionPane;
import nutri_advanced.Nutri_Advanced;
import nutri_advanced.Pag_Principal;
import Codigo.Conexion;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 * @author yordyg
 */
public class Evaluacion extends javax.swing.JFrame {
    
    private Conexion conexion = null; 
    private ResultSet rs = null;
    String id=null;
    
void Buscar(String var) 
    {
        try
        {
            conexion = new Conexion("alexis", "root", "com.mysql.jdbc.Driver", "NutriAdvanced");
            conexion.conecta();
            
            String consulta = "select * from Datos_Evaluacion where ID="+var;
            rs=conexion.Consultar(consulta);
        
            if(rs.next());
            {
                tPas.setText((rs.getString("ID")));
                FieldEdad.setText((rs.getString("Edad")));
                FieldPeso.setText((rs.getString("Peso")));
                FieldTalla.setText((rs.getString("Talla")));
                FieldCintura.setText((rs.getString("Cintura")));
                FieldCadera.setText((rs.getString("Cadera")));
            }
            
            String consulta2 = "select Nombre, Apellido from Pacientes where ID ="+var;
            rs=conexion.Consultar(consulta2);
            if(rs.next())
            {
                lNom.setText((rs.getString("Nombre")));
                lAp.setText((rs.getString("Apellido")));
            }
            id=tPas.getText();
        
        }
        catch (SQLException ex)
        {
			
            JOptionPane.showMessageDialog(null,ex, "Error", JOptionPane.ERROR_MESSAGE);
  	  	 
        }
        catch (Exception ex)
        {		
	    JOptionPane.showMessageDialog(null,ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }    

    public Evaluacion() {
        initComponents();
        buttonGroup1.add(RaBtnHombre);
        buttonGroup1.add(RaBtnMujer);
        
        buttonGroup2.add(RaBtnSedentario);
        buttonGroup2.add(RaBtnLeveActivo);
        buttonGroup2.add(RaBtnModeActivo);
        buttonGroup2.add(RaBtnMuyActivo);
        buttonGroup2.add(RaBtnHiper);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtqDatosEvaluacion = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        EtqPeso = new javax.swing.JLabel();
        EtqTalla = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        EtqCintura = new javax.swing.JLabel();
        EtqCadera = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        vTitlDatosEvaluacion = new javax.swing.JLabel();
        ePeso = new javax.swing.JLabel();
        eTalla = new javax.swing.JLabel();
        eCintura = new javax.swing.JLabel();
        eCadera = new javax.swing.JLabel();
        FieldPeso = new javax.swing.JTextField();
        FieldTalla = new javax.swing.JTextField();
        FieldCintura = new javax.swing.JTextField();
        FieldCadera = new javax.swing.JTextField();
        eTitResultados = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        eIMC = new javax.swing.JLabel();
        eClasificacion = new javax.swing.JLabel();
        ePesoIdeal = new javax.swing.JLabel();
        ePorcentajeGrasa = new javax.swing.JLabel();
        eMasaMagra = new javax.swing.JLabel();
        FieldIMC = new javax.swing.JTextField();
        FieldClasifi = new javax.swing.JTextField();
        FieldPesoIdeal = new javax.swing.JTextField();
        FieldPorcGrasa = new javax.swing.JTextField();
        FieldMasaMagra = new javax.swing.JTextField();
        RaBtnHombre = new javax.swing.JRadioButton();
        RaBtnMujer = new javax.swing.JRadioButton();
        eEdad = new javax.swing.JLabel();
        FieldEdad = new javax.swing.JTextField();
        FieldMetabolismoBasal = new javax.swing.JTextField();
        eMetabolismoBasal = new javax.swing.JLabel();
        eRequerimientoCalori = new javax.swing.JLabel();
        FieldRequeriCal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RaBtnSedentario = new javax.swing.JRadioButton();
        RaBtnLeveActivo = new javax.swing.JRadioButton();
        RaBtnModeActivo = new javax.swing.JRadioButton();
        RaBtnMuyActivo = new javax.swing.JRadioButton();
        RaBtnHiper = new javax.swing.JRadioButton();
        eCarbohidratos = new javax.swing.JLabel();
        eProteinas = new javax.swing.JLabel();
        eGrasas = new javax.swing.JLabel();
        FieldCarbohidratos = new javax.swing.JTextField();
        FieldProteinas = new javax.swing.JTextField();
        FieldGrasas = new javax.swing.JTextField();
        bRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_usuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tPas = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bCalcular = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        lNom = new javax.swing.JLabel();
        lAp = new javax.swing.JLabel();

        EtqDatosEvaluacion.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        EtqDatosEvaluacion.setText("DATOS DE EVALUACION");

        EtqPeso.setText("Peso");

        EtqTalla.setText("Talla");

        EtqCintura.setText("Cintura");

        EtqCadera.setText("Cadera");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        vTitlDatosEvaluacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vTitlDatosEvaluacion.setText("DATOS");

        ePeso.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        ePeso.setText("Peso");

        eTalla.setText("Talla");

        eCintura.setText("Cintura");

        eCadera.setText("Cadera");

        FieldPeso.setEditable(false);
        FieldPeso.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        FieldPeso.setBorder(null);

        FieldTalla.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        FieldTalla.setBorder(null);

        FieldCintura.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        FieldCintura.setBorder(null);
        FieldCintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCinturaActionPerformed(evt);
            }
        });

        FieldCadera.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        FieldCadera.setBorder(null);

        eTitResultados.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eTitResultados.setText("RESULTADOS");

        eIMC.setText("IMC");

        eClasificacion.setText("Clasificacion");

        ePesoIdeal.setText("Peso Ideal");

        ePorcentajeGrasa.setText("Porcentaje De Grasa");

        eMasaMagra.setText("Masa Magra");

        FieldClasifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldClasifiActionPerformed(evt);
            }
        });

        RaBtnHombre.setBackground(new java.awt.Color(255, 255, 255));
        RaBtnHombre.setText("Hombre");

        RaBtnMujer.setBackground(new java.awt.Color(255, 255, 255));
        RaBtnMujer.setText("Mujer");

        eEdad.setText("Edad");

        FieldEdad.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        FieldEdad.setBorder(null);

        eMetabolismoBasal.setText("MB");

        eRequerimientoCalori.setText("Requerimiento Cal.");

        FieldRequeriCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldRequeriCalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Nivel De Actividad Fisica");

        RaBtnSedentario.setBackground(new java.awt.Color(255, 255, 255));
        RaBtnSedentario.setText("Sedentario");
        RaBtnSedentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaBtnSedentarioActionPerformed(evt);
            }
        });

        RaBtnLeveActivo.setBackground(new java.awt.Color(255, 255, 255));
        RaBtnLeveActivo.setText("Levemente Activo");

        RaBtnModeActivo.setBackground(new java.awt.Color(255, 255, 255));
        RaBtnModeActivo.setText("Activo");

        RaBtnMuyActivo.setBackground(new java.awt.Color(255, 255, 255));
        RaBtnMuyActivo.setText("Muy Activo");

        RaBtnHiper.setBackground(new java.awt.Color(255, 255, 255));
        RaBtnHiper.setText("Hiperactivo ");

        eCarbohidratos.setText("Carbohidratos");

        eProteinas.setText("Proteinas");

        eGrasas.setText("Grasas");

        bRegresar.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        bRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        bRegresar.setBorderPainted(false);
        bRegresar.setContentAreaFilled(false);
        bRegresar.setEnabled(true);
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NUTRI-ADVANCED.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-nutriciónPequeñ.jpg"))); // NOI18N

        jLabel_usuario.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel_usuario.setText("Evaluación");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Paciente:");

        tPas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        bBuscar.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addusr.png"))); // NOI18N
        bBuscar.setBorderPainted(false);
        bBuscar.setContentAreaFilled(false);
        bBuscar.setEnabled(true);
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bCalcular.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        bCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Acept.png"))); // NOI18N
        bCalcular.setText("Aceptar");
        bCalcular.setBorderPainted(false);
        bCalcular.setContentAreaFilled(false);
        bCalcular.setEnabled(true);
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });

        bGuardar.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte copia.png"))); // NOI18N
        bGuardar.setText("Aceptar");
        bGuardar.setBorderPainted(false);
        bGuardar.setContentAreaFilled(false);
        bGuardar.setEnabled(true);
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        lNom.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        lAp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eTalla)
                            .addComponent(ePeso)
                            .addComponent(eEdad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_usuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FieldTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tPas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(FieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(FieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(eCadera)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(FieldCadera, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(eCintura)
                                                .addGap(34, 34, 34)
                                                .addComponent(FieldCintura, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(RaBtnHombre)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(RaBtnMujer)))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RaBtnSedentario)
                                            .addComponent(RaBtnModeActivo)
                                            .addComponent(RaBtnLeveActivo)
                                            .addComponent(RaBtnMuyActivo)
                                            .addComponent(RaBtnHiper)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(lNom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(lAp, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(22, 22, 22)
                        .addComponent(bCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(eClasificacion)
                                            .addComponent(eIMC, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ePesoIdeal, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(FieldIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FieldClasifi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FieldPesoIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(eMasaMagra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FieldMasaMagra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ePorcentajeGrasa)))
                            .addComponent(eTitResultados)
                            .addComponent(jLabel4)
                            .addComponent(vTitlDatosEvaluacion))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(FieldPorcGrasa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eMetabolismoBasal)
                    .addComponent(eRequerimientoCalori)
                    .addComponent(eCarbohidratos)
                    .addComponent(eProteinas)
                    .addComponent(eGrasas))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldMetabolismoBasal)
                            .addComponent(FieldRequeriCal)
                            .addComponent(FieldCarbohidratos)
                            .addComponent(FieldProteinas)
                            .addComponent(FieldGrasas, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_usuario)
                                    .addComponent(jLabel3))
                                .addGap(12, 12, 12)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addComponent(vTitlDatosEvaluacion)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNom)
                                    .addComponent(lAp))
                                .addGap(17, 17, 17)))))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ePeso)
                    .addComponent(FieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RaBtnHombre)
                    .addComponent(RaBtnMujer)
                    .addComponent(RaBtnSedentario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTalla, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eCintura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FieldTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FieldCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RaBtnLeveActivo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FieldCadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eCadera)
                                .addComponent(FieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RaBtnModeActivo))
                            .addComponent(eEdad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RaBtnMuyActivo)
                        .addGap(4, 4, 4)
                        .addComponent(RaBtnHiper))
                    .addComponent(bCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eTitResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eIMC)
                    .addComponent(FieldIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMetabolismoBasal)
                    .addComponent(FieldMetabolismoBasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eClasificacion)
                    .addComponent(FieldClasifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eRequerimientoCalori)
                    .addComponent(FieldRequeriCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ePesoIdeal)
                    .addComponent(FieldPesoIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eCarbohidratos)
                    .addComponent(FieldCarbohidratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldPorcGrasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ePorcentajeGrasa)
                    .addComponent(FieldProteinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eProteinas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldMasaMagra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMasaMagra)
                    .addComponent(FieldGrasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eGrasas))
                .addGap(43, 43, 43)
                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldCinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCinturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCinturaActionPerformed

    private void FieldClasifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldClasifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldClasifiActionPerformed

    private void FieldRequeriCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldRequeriCalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldRequeriCalActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        Pag_Principal pp = new Pag_Principal();
        pp.setVisible(true);
        dispose();
    }//GEN-LAST:event_bRegresarActionPerformed

    private void RaBtnSedentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaBtnSedentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RaBtnSedentarioActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        BuscarPac_1 bp = new BuscarPac_1();
        bp.setVisible(true);        
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
        if((FieldPeso.getText()).isEmpty()||(FieldTalla.getText()).isEmpty()||(FieldCintura.getText()).isEmpty()||(FieldCadera.getText()).isEmpty()||
           (FieldEdad.getText()).isEmpty()||(buttonGroup1.isSelected(null))||(buttonGroup2.isSelected(null)))
        {
        JOptionPane.showMessageDialog(null, "Llene Todos Los Campos");
        }
        else
        {
            
                    JOptionPane.showMessageDialog(null, "Correcto");
                    Nutri_Advanced formulas=new Nutri_Advanced();
                    float peso=Float.parseFloat(FieldPeso.getText());
                    float talla=Float.parseFloat(FieldTalla.getText());
                    int edad=Integer.parseInt(FieldEdad.getText());
                    char sexo;
                    int NumActi=0;
                    if(RaBtnHombre.isSelected()){sexo='1';}else{sexo='2';}
                        if(RaBtnSedentario.isSelected()){NumActi=1;}
                        if(RaBtnLeveActivo.isSelected()){NumActi=2;}
                        if(RaBtnModeActivo.isSelected()){NumActi=3;}
                        if(RaBtnMuyActivo.isSelected()){NumActi=4;}
                        if(RaBtnHiper.isSelected()){NumActi=5;}
                    
                    float imc=formulas.I_M_C(peso, talla);
                    float PorcGrasa=formulas.Porcentaje_grasa(imc, edad);
                    float MasaGrasa=formulas.Masa_Grasa(peso, PorcGrasa);
                    float MasaMagra=formulas.Masa_Magra(peso, MasaGrasa);
                    float MetabolismoBasal=formulas.MetabolismoBasal(MasaMagra);
                    float RequerimientoCaloritico=formulas.RequeCaloritico(MetabolismoBasal, NumActi);
                    float carbohidratos=formulas.carbono(RequerimientoCaloritico);
                    float proteinas=formulas.Proteina(RequerimientoCaloritico);
                    float grasas=formulas.Grasas(RequerimientoCaloritico);

                        

                        FieldIMC.setText(imc+"");
                        FieldClasifi.setText(formulas.Clasificacion_IMC(imc));
                        FieldPesoIdeal.setText((formulas.P_Ideal(talla, sexo))+"");
                        FieldPorcGrasa.setText(PorcGrasa+"");
                        FieldMasaMagra.setText(MasaMagra+"");
                        FieldMetabolismoBasal.setText(MetabolismoBasal+"");
                        FieldRequeriCal.setText(RequerimientoCaloritico+"");
                        FieldCarbohidratos.setText(carbohidratos+"");
                        FieldProteinas.setText(proteinas+"");
                        FieldGrasas.setText(grasas+"");
//                      FieldMasaGrasa.setText(MasaGrasa+"");
//                      float Agua=formulas.Agua_Corporal_Total(sexo, peso, edad);
//                      FieldAgCorporal.setText(Agua+"");
//                      float AguaIntra=formulas.Agua_Corporal_Intracelular(Agua, edad, sexo);
//                      FieldAgIntraCe.setText(AguaIntra+"");
//                      float AguaExtra=formulas.Agua_Corporal_Extracelular(Agua, AguaIntra);
//                      FieldAgExtraCel.setText(AguaExtra+"");
//                      FieldCaderaCintura.setText((formulas.Cintura_Cadera(cintura, cadera))+"");            
        }
    }//GEN-LAST:event_bCalcularActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        
        conexion = new Conexion("alexis", "root", "com.mysql.jdbc.Driver", "NutriAdvanced");
        conexion.conecta();
        
        String id = tPas.getText();
        String imc = FieldIMC.getText();
        String clas = FieldClasifi.getText();
        String pi = FieldPesoIdeal.getText();
        String pg = FieldPorcGrasa.getText();
        String mm = FieldMasaMagra.getText();
        String mb = FieldMetabolismoBasal.getText();
        String rc = FieldRequeriCal.getText();
        String car = FieldCarbohidratos.getText();
        String prot = FieldProteinas.getText();
        String gr = FieldGrasas.getText();
        
        String insert = "insert into Evaluaciones values(null,'"+id+"', current_date(), '"+imc+"', '"+clas+"', '"+pi+"', '"+pg+"', '"+mm+"', '"+mb+"', '"+rc+"', '"+car+"', '"+prot+"', '"+gr+"')";
        
        try
        {
            conexion.insertaRegistro(insert);
            System.out.println("Registrado");
        }
	catch (Exception ex)
	{
		JOptionPane.showMessageDialog(null,"Fallo la Conexión", "Error", JOptionPane.ERROR_MESSAGE);//Error java
	}
        
        JOptionPane.showMessageDialog(null,"La Evaluacion fue exitosa");
        PDF pdf=new PDF();
        pdf.CrearPDF(id, FieldPeso.getText(), FieldTalla.getText(), imc, clas, pi, pg, mm, mb, rc, car, prot, gr);
        
        dispose();
    }//GEN-LAST:event_bGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtqCadera;
    private javax.swing.JLabel EtqCintura;
    private javax.swing.JLabel EtqDatosEvaluacion;
    private javax.swing.JLabel EtqPeso;
    private javax.swing.JLabel EtqTalla;
    private javax.swing.JTextField FieldCadera;
    private javax.swing.JTextField FieldCarbohidratos;
    private javax.swing.JTextField FieldCintura;
    private javax.swing.JTextField FieldClasifi;
    private javax.swing.JTextField FieldEdad;
    private javax.swing.JTextField FieldGrasas;
    private javax.swing.JTextField FieldIMC;
    private javax.swing.JTextField FieldMasaMagra;
    private javax.swing.JTextField FieldMetabolismoBasal;
    private javax.swing.JTextField FieldPeso;
    private javax.swing.JTextField FieldPesoIdeal;
    private javax.swing.JTextField FieldPorcGrasa;
    private javax.swing.JTextField FieldProteinas;
    private javax.swing.JTextField FieldRequeriCal;
    private javax.swing.JTextField FieldTalla;
    private javax.swing.JRadioButton RaBtnHiper;
    private javax.swing.JRadioButton RaBtnHombre;
    private javax.swing.JRadioButton RaBtnLeveActivo;
    private javax.swing.JRadioButton RaBtnModeActivo;
    private javax.swing.JRadioButton RaBtnMujer;
    private javax.swing.JRadioButton RaBtnMuyActivo;
    private javax.swing.JRadioButton RaBtnSedentario;
    public javax.swing.JButton bBuscar;
    public javax.swing.JButton bCalcular;
    public javax.swing.JButton bGuardar;
    public javax.swing.JButton bRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel eCadera;
    private javax.swing.JLabel eCarbohidratos;
    private javax.swing.JLabel eCintura;
    private javax.swing.JLabel eClasificacion;
    private javax.swing.JLabel eEdad;
    private javax.swing.JLabel eGrasas;
    private javax.swing.JLabel eIMC;
    private javax.swing.JLabel eMasaMagra;
    private javax.swing.JLabel eMetabolismoBasal;
    private javax.swing.JLabel ePeso;
    private javax.swing.JLabel ePesoIdeal;
    private javax.swing.JLabel ePorcentajeGrasa;
    private javax.swing.JLabel eProteinas;
    private javax.swing.JLabel eRequerimientoCalori;
    private javax.swing.JLabel eTalla;
    private javax.swing.JLabel eTitResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lAp;
    private javax.swing.JLabel lNom;
    private javax.swing.JTextField tPas;
    private javax.swing.JLabel vTitlDatosEvaluacion;
    // End of variables declaration//GEN-END:variables
}
